x-stateless: &stateless
  network_mode: none
  deploy:
    replicas: 0

services:
  php7:
    image: ${DOCKER_IMAGE_PREFIX?:}/php:7-onbuild
    build:
      context: src/php
      dockerfile: php7.Dockerfile
      target: release
    <<: *stateless

  php8:
    image: ${DOCKER_IMAGE_PREFIX?:}/php:8-onbuild
    build:
      context: src/php
      dockerfile: php8.Dockerfile
      target: release
    <<: *stateless

  node20:
    image: ${DOCKER_IMAGE_PREFIX?:}/node:20-onbuild
    build:
      context: src/node
      dockerfile: node20.Dockerfile
      target: release
    <<: *stateless

  python3:
    image: ${DOCKER_IMAGE_PREFIX?:}/python:3-onbuild
    build:
      context: src/python
      dockerfile: python3.Dockerfile
      target: release
    <<: *stateless

  ruby3:
    image: ${DOCKER_IMAGE_PREFIX?:}/ruby:3-onbuild
    build:
      context: src/ruby
      dockerfile: ruby3.Dockerfile
      target: release
    <<: *stateless
