x-stateless: &stateless
  network_mode: none
  deploy:
    replicas: 0

services:
  php7:
    image: ${DOCKER_IMAGE_PREFIX}/php:7-onbuild
    build:
      context: php
      dockerfile: php7.Dockerfile
      target: release
    <<: *stateless

  php8:
    image: ${DOCKER_IMAGE_PREFIX}/php:8-onbuild
    build:
      context: php
      dockerfile: php8.Dockerfile
      target: release
    <<: *stateless

  node20:
    image: ${DOCKER_IMAGE_PREFIX}/node:20-onbuild
    build:
      context: node
      dockerfile: node20.Dockerfile
      target: release
    <<: *stateless
