version: '2.4'

services:
  php7:
    build:
      context: php
      dockerfile: php7.Dockerfile
      target: cli
    image: ghcr.io/h0riz0ns/php:7-onbuild

  php7-fpm:
    build:
      context: php
      dockerfile: php7.Dockerfile
      target: fpm
    image: ghcr.io/h0riz0ns/php:7-fpm-onbuild

  node16:
    build:
      context: node
      dockerfile: node16.Dockerfile
    image: ghcr.io/h0riz0ns/node:16-onbuild
