name: docker-images

services:
  php7:
    build:
      context: php
      dockerfile: php7.Dockerfile
    image: ${DOCKER_IMAGE_PREFIX}/php:7-onbuild
    network_mode: none
    deploy:
      replicas: 0

  node16:
    build:
      context: node
      dockerfile: node16.Dockerfile
    image: ${DOCKER_IMAGE_PREFIX}/node:16-onbuild
    network_mode: none
    deploy:
      replicas: 0
