name: Manual release

on: workflow_dispatch

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: make release
