name: Release

on:
  push:
    branches:
      - master
    paths:
      - docker-compose.yml
      - php/**
      - node/**

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: make release
