name: release

on:
  workflow_dispatch: ~

  workflow_run:
    branches:
      - master
    workflows:
      - tests-and-QA
    types:
      - completed

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  build-and-push:
    if: github.ref == 'refs/heads/master' && (!github.event.workflow_run || github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - run: make release
