name: release

on:
  workflow_dispatch: ~

  workflow_run:
    branches:
      - main
    workflows:
      - tests-and-QA
    types:
      - completed

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  build-and-push:
    if: github.ref == 'refs/heads/main' && (!github.event.workflow_run || github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-22.04
    env:
      COMPOSE_ENV_FILES: .env.release
    steps:
      - uses: ndeloof/install-compose-action@main
        with:
          version: v2.29.2

      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - run: make release
        env:
          DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
          DOCKER_IMAGE_NAMESPACE: ${{ vars.DOCKER_IMAGE_NAMESPACE }}
