name: tests-and-QA

on:
  push: ~

concurrency:
  group: tests-and-QA_${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: ndeloof/install-compose-action@main
        with:
          version: v2.29.2

      - uses: actions/checkout@v4

      - run: make test
