name: tests-and-QA

on:
  push: ~

concurrency:
  group: test-and-QA_${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: make test
