name: Tests and QA checks

on:
  push: ~

concurrency:
  group: test--${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: make test.build
      - run: make test.run
